### ISSUE TITLE
Do you plan to change you license to MIT ?

### ISSUE THREAD

**Issue by mackoj** [mikeger/XcodeSelectiveTesting#9]
Hi,

Thanks for making this great library.

Do you plan to change your license to MIT? Because GPL is not acceptable for many companies.

Using a library under the GPL-3.0 (GNU General Public License, version 3.0) license in your app for distribution on the Apple App Store can be challenging due to the terms of the GPL-3.0 license, which is a strong copyleft license. The GPL-3.0 has certain requirements, including the obligation to make your source code available if you distribute a program that uses GPL-3.0-licensed code.

When you distribute an app through the Apple App Store, you don't typically provide access to the app's source code, which could be a problem when using GPL-3.0-licensed code. You would need to provide the source code for the entire app, not just the modified parts related to the GPL-3.0-licensed library.

**Comment by mackoj** [comment]
I’m sorry to bother you, @mikeger. Have you had a chance to consider my request?

**Comment by mikeger** [comment]
Hey @mackoj ! Thanks for opening an issue. For some reason, I got no notification for it.

You are correct that the libraries licensed under GPLv3 are not compatible with the App Store. However, this project is not a library and is not linked to your app. Therefore is not going to be distributed through the App Store. It is a command line tool and Xcode plugin that runs on the developer's machine.

I hope this clarifies the matter. Feel free to reach out if you need any further support.

**Comment by mackoj** [comment]
I understand your perspective, but company policies are not always very flexible, and those who enforce and promote them may not fully grasp the intricacies of how SPM works.

Thank you for taking the time to respond.

**Comment by mikeger** [comment]
I see your point, please allow me some time to consider the licensing change.

**Comment by mackoj** [comment]
Thanks

**Comment by mikeger** [comment]
Hey @mackoj I re-licensed the tool under the MIT license, I hope it will help you and others to adopt it more easily.
